version: '3.8'

services:
  postgres:
    container_name: postgres-sql-ss
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring_security
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-ss
    image: maildev/maildev
    environment:
      - MAILDEV_SMTP_DISABLE_AUTH_LOGIN=true
      - MAILDEV_SMTP_DISABLE_AUTH_PLAIN=true
      - MAILDEV_SMTP_DISABLE_STARTTLS=true
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
