#this inherits from application.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mail:
  host: mail-dev
  port: 1025
  properties:
    mail:
      smtp:
        auth: false
        starttls:
          enable: false
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
        fallback: false

application:
  security:
    jwt:
      secret-key: 2C2BB4D5134E15A76B3B46981BB34
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088